"""Public API for the A_memorix memory engine."""

from typing import Any

from .adapter_manifest import (
    ADAPTER_MANIFEST_SCHEMA_VERSION,
    ADAPTER_PROTOCOL_VERSION,
    AdapterApiPermission,
    AdapterCompatibilityError,
    AdapterFilesystemPermission,
    AdapterHostPort,
    AdapterManifest,
    AdapterPermissions,
    AdapterRuntime,
    AdapterTransport,
    FilesystemAccess,
    adapter_manifest_json_schema,
    ensure_adapter_compatible,
    load_adapter_manifest,
)
from .contracts import (
    AMemorixError,
    ApiKeyInfo,
    BatchIngestItemResult,
    BatchIngestTextRequest,
    BatchIngestTextResponse,
    CapabilityUnavailableError,
    CreateNamespaceRequest,
    CreatedApiKey,
    DeleteBySourceRequest,
    DeleteMemoryRequest,
    DeleteMemoryResponse,
    ErrorCode,
    ErrorEnvelope,
    ForbiddenError,
    GetMemoryRequest,
    GetMemoryResponse,
    IngestTextInput,
    IngestTextRequest,
    IngestTextResponse,
    InvalidArgumentError,
    JobInfo,
    JobStatus,
    JobType,
    MigrationRequiredError,
    MemoryHit,
    MemoryRecord,
    NAMESPACE_BACKUP_FORMAT,
    NAMESPACE_BACKUP_FORMAT_VERSION,
    NotFoundError,
    NamespaceBackupChunk,
    NamespaceBackupFile,
    NamespaceBackupInfo,
    NamespaceBackupManifest,
    NamespaceBackupUpload,
    NamespaceCapacityError,
    NamespaceCapabilities,
    NamespaceConfig,
    NamespaceFeatureConfig,
    NamespaceConflictError,
    NamespaceHealth,
    NamespaceInfo,
    NamespaceIntegrityError,
    NamespaceNotFoundError,
    NamespaceQuota,
    RelationExtractionConfig,
    NamespaceRuntimeError,
    NamespaceStateError,
    NamespaceStatus,
    RequestContext,
    RelationInput,
    RelationExtractionMode,
    RestoreNamespaceBackupRequest,
    ProviderReference,
    RemoteAMemorixError,
    SearchMemoryRequest,
    SearchMemoryResponse,
    SearchMode,
    UnauthorizedError,
    UpdateNamespaceConfigRequest,
)
from .core.runtime import KernelSearchRequest, SDKMemoryKernel
from .engine import AMemorixEngine
from .ports import (
    Clock,
    EmbeddingProvider,
    IdentityRecord,
    IdentityResolver,
    LLMProvider,
    LLMRequest,
    LLMResult,
    MessageRecord,
    MessageSource,
    NamespaceHostPorts,
    SystemClock,
)

__all__ = [
    "ADAPTER_MANIFEST_SCHEMA_VERSION",
    "ADAPTER_PROTOCOL_VERSION",
    "AMemorixEngine",
    "AMemorixError",
    "AMemorixClient",
    "ApiKeyInfo",
    "AdapterApiPermission",
    "AdapterCompatibilityError",
    "AdapterFilesystemPermission",
    "AdapterHostPort",
    "AdapterManifest",
    "AdapterPermissions",
    "AdapterRuntime",
    "AdapterTransport",
    "BatchIngestItemResult",
    "BatchIngestTextRequest",
    "BatchIngestTextResponse",
    "CapabilityUnavailableError",
    "Clock",
    "CreateNamespaceRequest",
    "CreatedApiKey",
    "DeleteBySourceRequest",
    "DeleteMemoryRequest",
    "DeleteMemoryResponse",
    "create_fixed_namespace_mcp",
    "EmbeddingProvider",
    "ErrorCode",
    "ErrorEnvelope",
    "ForbiddenError",
    "FilesystemAccess",
    "GetMemoryRequest",
    "GetMemoryResponse",
    "IngestTextInput",
    "IngestTextRequest",
    "IngestTextResponse",
    "InvalidArgumentError",
    "JobInfo",
    "JobStatus",
    "JobType",
    "IdentityRecord",
    "IdentityResolver",
    "KernelSearchRequest",
    "LLMProvider",
    "LLMRequest",
    "LLMResult",
    "MessageRecord",
    "MessageSource",
    "MigrationRequiredError",
    "MemoryHit",
    "MemoryRecord",
    "NAMESPACE_BACKUP_FORMAT",
    "NAMESPACE_BACKUP_FORMAT_VERSION",
    "NamespaceCapacityError",
    "NamespaceBackupChunk",
    "NamespaceBackupFile",
    "NamespaceBackupInfo",
    "NamespaceBackupManifest",
    "NamespaceBackupUpload",
    "NamespaceCapabilities",
    "NamespaceConfig",
    "NamespaceFeatureConfig",
    "NamespaceConflictError",
    "NamespaceHealth",
    "NamespaceHostPorts",
    "NamespaceInfo",
    "NamespaceIntegrityError",
    "NamespaceNotFoundError",
    "NamespaceQuota",
    "NamespaceRuntimeError",
    "NamespaceStateError",
    "NamespaceStatus",
    "NotFoundError",
    "RequestContext",
    "RelationInput",
    "RelationExtractionConfig",
    "RelationExtractionMode",
    "RestoreNamespaceBackupRequest",
    "ProviderReference",
    "RemoteAMemorixError",
    "SDKMemoryKernel",
    "SearchMemoryRequest",
    "SearchMemoryResponse",
    "SearchMode",
    "SystemClock",
    "UnauthorizedError",
    "UpdateNamespaceConfigRequest",
    "adapter_manifest_json_schema",
    "ensure_adapter_compatible",
    "load_adapter_manifest",
    "__version__",
]
__version__ = "2.0.0a2"


def __getattr__(name: str) -> Any:
    if name == "AMemorixClient":
        try:
            from .client import AMemorixClient
        except ModuleNotFoundError as exc:
            raise ModuleNotFoundError(
                "AMemorixClient requires the 'rpc' extra: pip install 'a-memorix[rpc]'"
            ) from exc
        return AMemorixClient
    if name == "create_fixed_namespace_mcp":
        try:
            from .mcp_server import create_fixed_namespace_mcp
        except ModuleNotFoundError as exc:
            raise ModuleNotFoundError(
                "MCP support requires the 'mcp' extra: pip install 'a-memorix[mcp]'"
            ) from exc
        return create_fixed_namespace_mcp
    raise AttributeError(name)
