# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from a_memorix.api.v1 import auth_pb2 as a__memorix_dot_api_dot_v1_dot_auth__pb2


class AuthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateApiKey = channel.unary_unary(
                '/a_memorix.api.v1.AuthService/CreateApiKey',
                request_serializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.CreateApiKeyRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.CreateApiKeyResponse.FromString,
                _registered_method=True)
        self.ListApiKeys = channel.unary_unary(
                '/a_memorix.api.v1.AuthService/ListApiKeys',
                request_serializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.ListApiKeysRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.ListApiKeysResponse.FromString,
                _registered_method=True)
        self.RevokeApiKey = channel.unary_unary(
                '/a_memorix.api.v1.AuthService/RevokeApiKey',
                request_serializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.RevokeApiKeyRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.RevokeApiKeyResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiKey,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.CreateApiKeyRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.CreateApiKeyResponse.SerializeToString,
            ),
            'ListApiKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiKeys,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.ListApiKeysRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.ListApiKeysResponse.SerializeToString,
            ),
            'RevokeApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeApiKey,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.RevokeApiKeyRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_auth__pb2.RevokeApiKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a_memorix.api.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a_memorix.api.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.AuthService/CreateApiKey',
            a__memorix_dot_api_dot_v1_dot_auth__pb2.CreateApiKeyRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_auth__pb2.CreateApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApiKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.AuthService/ListApiKeys',
            a__memorix_dot_api_dot_v1_dot_auth__pb2.ListApiKeysRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_auth__pb2.ListApiKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.AuthService/RevokeApiKey',
            a__memorix_dot_api_dot_v1_dot_auth__pb2.RevokeApiKeyRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_auth__pb2.RevokeApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
