# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from a_memorix.api.v1 import backup_pb2 as a__memorix_dot_api_dot_v1_dot_backup__pb2


class BackupServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNamespaceBackup = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/CreateNamespaceBackup',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.CreateNamespaceBackupRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.CreateNamespaceBackupResponse.FromString,
                _registered_method=True)
        self.GetNamespaceBackup = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/GetNamespaceBackup',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.GetNamespaceBackupRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.GetNamespaceBackupResponse.FromString,
                _registered_method=True)
        self.ListNamespaceBackups = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/ListNamespaceBackups',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.ListNamespaceBackupsRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.ListNamespaceBackupsResponse.FromString,
                _registered_method=True)
        self.DeleteNamespaceBackup = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/DeleteNamespaceBackup',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.DeleteNamespaceBackupRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.DeleteNamespaceBackupResponse.FromString,
                _registered_method=True)
        self.DownloadNamespaceBackup = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/DownloadNamespaceBackup',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.DownloadNamespaceBackupRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.DownloadNamespaceBackupResponse.FromString,
                _registered_method=True)
        self.BeginNamespaceBackupUpload = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/BeginNamespaceBackupUpload',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.BeginNamespaceBackupUploadRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.BeginNamespaceBackupUploadResponse.FromString,
                _registered_method=True)
        self.UploadNamespaceBackupChunk = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/UploadNamespaceBackupChunk',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.UploadNamespaceBackupChunkRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.UploadNamespaceBackupChunkResponse.FromString,
                _registered_method=True)
        self.CompleteNamespaceBackupUpload = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/CompleteNamespaceBackupUpload',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.CompleteNamespaceBackupUploadRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.CompleteNamespaceBackupUploadResponse.FromString,
                _registered_method=True)
        self.AbortNamespaceBackupUpload = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/AbortNamespaceBackupUpload',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.AbortNamespaceBackupUploadRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.AbortNamespaceBackupUploadResponse.FromString,
                _registered_method=True)
        self.RestoreNamespaceFromBackup = channel.unary_unary(
                '/a_memorix.api.v1.BackupService/RestoreNamespaceFromBackup',
                request_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.RestoreNamespaceFromBackupRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.RestoreNamespaceFromBackupResponse.FromString,
                _registered_method=True)


class BackupServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateNamespaceBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNamespaceBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaceBackups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNamespaceBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadNamespaceBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginNamespaceBackupUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadNamespaceBackupChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteNamespaceBackupUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortNamespaceBackupUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreNamespaceFromBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNamespaceBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNamespaceBackup,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.CreateNamespaceBackupRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.CreateNamespaceBackupResponse.SerializeToString,
            ),
            'GetNamespaceBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNamespaceBackup,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.GetNamespaceBackupRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.GetNamespaceBackupResponse.SerializeToString,
            ),
            'ListNamespaceBackups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaceBackups,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.ListNamespaceBackupsRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.ListNamespaceBackupsResponse.SerializeToString,
            ),
            'DeleteNamespaceBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNamespaceBackup,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.DeleteNamespaceBackupRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.DeleteNamespaceBackupResponse.SerializeToString,
            ),
            'DownloadNamespaceBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadNamespaceBackup,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.DownloadNamespaceBackupRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.DownloadNamespaceBackupResponse.SerializeToString,
            ),
            'BeginNamespaceBackupUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginNamespaceBackupUpload,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.BeginNamespaceBackupUploadRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.BeginNamespaceBackupUploadResponse.SerializeToString,
            ),
            'UploadNamespaceBackupChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadNamespaceBackupChunk,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.UploadNamespaceBackupChunkRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.UploadNamespaceBackupChunkResponse.SerializeToString,
            ),
            'CompleteNamespaceBackupUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteNamespaceBackupUpload,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.CompleteNamespaceBackupUploadRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.CompleteNamespaceBackupUploadResponse.SerializeToString,
            ),
            'AbortNamespaceBackupUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortNamespaceBackupUpload,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.AbortNamespaceBackupUploadRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.AbortNamespaceBackupUploadResponse.SerializeToString,
            ),
            'RestoreNamespaceFromBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreNamespaceFromBackup,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.RestoreNamespaceFromBackupRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_backup__pb2.RestoreNamespaceFromBackupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a_memorix.api.v1.BackupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a_memorix.api.v1.BackupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BackupService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNamespaceBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/CreateNamespaceBackup',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.CreateNamespaceBackupRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.CreateNamespaceBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNamespaceBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/GetNamespaceBackup',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.GetNamespaceBackupRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.GetNamespaceBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaceBackups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/ListNamespaceBackups',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.ListNamespaceBackupsRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.ListNamespaceBackupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNamespaceBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/DeleteNamespaceBackup',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.DeleteNamespaceBackupRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.DeleteNamespaceBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadNamespaceBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/DownloadNamespaceBackup',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.DownloadNamespaceBackupRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.DownloadNamespaceBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginNamespaceBackupUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/BeginNamespaceBackupUpload',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.BeginNamespaceBackupUploadRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.BeginNamespaceBackupUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadNamespaceBackupChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/UploadNamespaceBackupChunk',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.UploadNamespaceBackupChunkRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.UploadNamespaceBackupChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteNamespaceBackupUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/CompleteNamespaceBackupUpload',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.CompleteNamespaceBackupUploadRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.CompleteNamespaceBackupUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortNamespaceBackupUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/AbortNamespaceBackupUpload',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.AbortNamespaceBackupUploadRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.AbortNamespaceBackupUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreNamespaceFromBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.BackupService/RestoreNamespaceFromBackup',
            a__memorix_dot_api_dot_v1_dot_backup__pb2.RestoreNamespaceFromBackupRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_backup__pb2.RestoreNamespaceFromBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
