# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a_memorix/api/v1/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'a_memorix/api/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61_memorix/api/v1/common.proto\x12\x10\x61_memorix.api.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb1\x02\n\x0eRequestContext\x12!\n\x0cnamespace_id\x18\x01 \x01(\tR\x0bnamespaceId\x12\x19\n\x08\x61gent_id\x18\x02 \x01(\tR\x07\x61gentId\x12!\n\x0cprincipal_id\x18\x03 \x01(\tR\x0bprincipalId\x12\'\n\x0f\x63onversation_id\x18\x04 \x01(\tR\x0e\x63onversationId\x12\x17\n\x07user_id\x18\x05 \x01(\tR\x06userId\x12\x19\n\x08group_id\x18\x06 \x01(\tR\x07groupId\x12\x1d\n\nrequest_id\x18\x07 \x01(\tR\trequestId\x12\x19\n\x08trace_id\x18\x08 \x01(\tR\x07traceId\x12\'\n\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\"\xac\x01\n\x0b\x45rrorDetail\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x1d\n\nrequest_id\x18\x02 \x01(\tR\trequestId\x12\x19\n\x08trace_id\x18\x03 \x01(\tR\x07traceId\x12\x1c\n\tretryable\x18\x04 \x01(\x08R\tretryable\x12\x31\n\x07\x64\x65tails\x18\x05 \x01(\x0b\x32\x17.google.protobuf.StructR\x07\x64\x65tailsB\xc1\x01\n\x14\x63om.a_memorix.api.v1B\x0b\x43ommonProtoP\x01Z>github.com/MaiM-with-u/A_memorix/gen/go/a_memorix/api/v1;apiv1\xa2\x02\x03\x41\x41X\xaa\x02\x0f\x41Memorix.Api.V1\xca\x02\x0f\x41Memorix\\Api\\V1\xe2\x02\x1b\x41Memorix\\Api\\V1\\GPBMetadata\xea\x02\x11\x41Memorix::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a_memorix.api.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.a_memorix.api.v1B\013CommonProtoP\001Z>github.com/MaiM-with-u/A_memorix/gen/go/a_memorix/api/v1;apiv1\242\002\003AAX\252\002\017AMemorix.Api.V1\312\002\017AMemorix\\Api\\V1\342\002\033AMemorix\\Api\\V1\\GPBMetadata\352\002\021AMemorix::Api::V1'
  _globals['_REQUESTCONTEXT']._serialized_start=82
  _globals['_REQUESTCONTEXT']._serialized_end=387
  _globals['_ERRORDETAIL']._serialized_start=390
  _globals['_ERRORDETAIL']._serialized_end=562
# @@protoc_insertion_point(module_scope)
