# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from a_memorix.api.v1 import job_pb2 as a__memorix_dot_api_dot_v1_dot_job__pb2


class JobServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitDeleteBySource = channel.unary_unary(
                '/a_memorix.api.v1.JobService/SubmitDeleteBySource',
                request_serializer=a__memorix_dot_api_dot_v1_dot_job__pb2.SubmitDeleteBySourceRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_job__pb2.SubmitDeleteBySourceResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/a_memorix.api.v1.JobService/GetJob',
                request_serializer=a__memorix_dot_api_dot_v1_dot_job__pb2.GetJobRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_job__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/a_memorix.api.v1.JobService/ListJobs',
                request_serializer=a__memorix_dot_api_dot_v1_dot_job__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_job__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/a_memorix.api.v1.JobService/CancelJob',
                request_serializer=a__memorix_dot_api_dot_v1_dot_job__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_job__pb2.CancelJobResponse.FromString,
                _registered_method=True)


class JobServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SubmitDeleteBySource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitDeleteBySource': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitDeleteBySource,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_job__pb2.SubmitDeleteBySourceRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_job__pb2.SubmitDeleteBySourceResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_job__pb2.GetJobRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_job__pb2.GetJobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_job__pb2.ListJobsRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_job__pb2.ListJobsResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_job__pb2.CancelJobRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_job__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a_memorix.api.v1.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a_memorix.api.v1.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitDeleteBySource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.JobService/SubmitDeleteBySource',
            a__memorix_dot_api_dot_v1_dot_job__pb2.SubmitDeleteBySourceRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_job__pb2.SubmitDeleteBySourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.JobService/GetJob',
            a__memorix_dot_api_dot_v1_dot_job__pb2.GetJobRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_job__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.JobService/ListJobs',
            a__memorix_dot_api_dot_v1_dot_job__pb2.ListJobsRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_job__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.JobService/CancelJob',
            a__memorix_dot_api_dot_v1_dot_job__pb2.CancelJobRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_job__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
