# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from a_memorix.api.v1 import memory_pb2 as a__memorix_dot_api_dot_v1_dot_memory__pb2


class MemoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestText = channel.unary_unary(
                '/a_memorix.api.v1.MemoryService/IngestText',
                request_serializer=a__memorix_dot_api_dot_v1_dot_memory__pb2.IngestTextRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_memory__pb2.IngestTextResponse.FromString,
                _registered_method=True)
        self.SearchMemory = channel.unary_unary(
                '/a_memorix.api.v1.MemoryService/SearchMemory',
                request_serializer=a__memorix_dot_api_dot_v1_dot_memory__pb2.SearchMemoryRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_memory__pb2.SearchMemoryResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def IngestText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestText': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestText,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_memory__pb2.IngestTextRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_memory__pb2.IngestTextResponse.SerializeToString,
            ),
            'SearchMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemory,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_memory__pb2.SearchMemoryRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_memory__pb2.SearchMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a_memorix.api.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a_memorix.api.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.MemoryService/IngestText',
            a__memorix_dot_api_dot_v1_dot_memory__pb2.IngestTextRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_memory__pb2.IngestTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.MemoryService/SearchMemory',
            a__memorix_dot_api_dot_v1_dot_memory__pb2.SearchMemoryRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_memory__pb2.SearchMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
