# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from a_memorix.api.v1 import namespace_pb2 as a__memorix_dot_api_dot_v1_dot_namespace__pb2


class NamespaceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNamespace = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/CreateNamespace',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.CreateNamespaceRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.CreateNamespaceResponse.FromString,
                _registered_method=True)
        self.GetNamespace = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/GetNamespace',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceResponse.FromString,
                _registered_method=True)
        self.ListNamespaces = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/ListNamespaces',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)
        self.DisableNamespace = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/DisableNamespace',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.DisableNamespaceRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.DisableNamespaceResponse.FromString,
                _registered_method=True)
        self.EnableNamespace = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/EnableNamespace',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.EnableNamespaceRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.EnableNamespaceResponse.FromString,
                _registered_method=True)
        self.DeleteNamespace = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/DeleteNamespace',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.DeleteNamespaceRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.DeleteNamespaceResponse.FromString,
                _registered_method=True)
        self.RestoreNamespace = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/RestoreNamespace',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.RestoreNamespaceRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.RestoreNamespaceResponse.FromString,
                _registered_method=True)
        self.PurgeNamespace = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/PurgeNamespace',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.PurgeNamespaceRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.PurgeNamespaceResponse.FromString,
                _registered_method=True)
        self.GetNamespaceHealth = channel.unary_unary(
                '/a_memorix.api.v1.NamespaceService/GetNamespaceHealth',
                request_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceHealthRequest.SerializeToString,
                response_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceHealthResponse.FromString,
                _registered_method=True)


class NamespaceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNamespaceHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NamespaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNamespace,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.CreateNamespaceRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.CreateNamespaceResponse.SerializeToString,
            ),
            'GetNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNamespace,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceResponse.SerializeToString,
            ),
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.ListNamespacesRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.ListNamespacesResponse.SerializeToString,
            ),
            'DisableNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableNamespace,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.DisableNamespaceRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.DisableNamespaceResponse.SerializeToString,
            ),
            'EnableNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableNamespace,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.EnableNamespaceRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.EnableNamespaceResponse.SerializeToString,
            ),
            'DeleteNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNamespace,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.DeleteNamespaceRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.DeleteNamespaceResponse.SerializeToString,
            ),
            'RestoreNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreNamespace,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.RestoreNamespaceRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.RestoreNamespaceResponse.SerializeToString,
            ),
            'PurgeNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeNamespace,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.PurgeNamespaceRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.PurgeNamespaceResponse.SerializeToString,
            ),
            'GetNamespaceHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNamespaceHealth,
                    request_deserializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceHealthRequest.FromString,
                    response_serializer=a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a_memorix.api.v1.NamespaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a_memorix.api.v1.NamespaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NamespaceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/CreateNamespace',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.CreateNamespaceRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.CreateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/GetNamespace',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/ListNamespaces',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.ListNamespacesRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/DisableNamespace',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.DisableNamespaceRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.DisableNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/EnableNamespace',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.EnableNamespaceRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.EnableNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/DeleteNamespace',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.DeleteNamespaceRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.DeleteNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/RestoreNamespace',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.RestoreNamespaceRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.RestoreNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/PurgeNamespace',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.PurgeNamespaceRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.PurgeNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNamespaceHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a_memorix.api.v1.NamespaceService/GetNamespaceHealth',
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceHealthRequest.SerializeToString,
            a__memorix_dot_api_dot_v1_dot_namespace__pb2.GetNamespaceHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
